# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-05 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earth', '0003_auto_20160830_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='关于作者')),
            ],
        ),
    ]
