# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('disk', models.CharField(max_length=50)),
                ('vendor_id', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('Manufacturer', models.CharField(max_length=50)),
                ('sn', models.CharField(max_length=50)),
            ],
        ),
    ]
